### ISSUE TITLE
getting error Cannot find module 'nodent-runtime'

### ISSUE THREAD

**Issue by bdwain** [sebastian-software/rollup-plugin-rebase#5]
I'm getting an error when trying to pull in rebase to my project. i don't even need to include it in my config object, i just need to require it. 

`const rebasePlugin = require('rollup-plugin-rebase');`

Adding that to a valid config causes the error. 

```
[!] Error: Cannot find module 'nodent-runtime'
Error: Cannot find module 'nodent-runtime'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/bwain/dev/my-project/node_modules/rollup-plugin-rebase/lib/node.commonjs.js:6:37)
    at Module._compile (module.js:624:30)
    at Module._extensions..js (module.js:635:10)
    at Object.require.extensions..js (/Users/bwain/dev/my-project/node_modules/rollup/bin/rollup:2677:6)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
```

is it possible that's a dependency and not specified somewhere? I can't even `yarn add nodent-runtime` so i'm not sure what that's about.

It also would be helpful to post a more complete example with options being used as the current example is a little confusing.

Thanks!

**Comment by swernerx** [comment]
Thanks for the report. This was indeed a missing dependency. Should be fixed in the newest release: 0.11.4.
